name: Deploy to OSS @ vNext

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        working-directory: ./packages/website
        run: yarn build
        env:
          CI: false
          REACT_APP_USE_CONFIG_FILE: 1
      - name: Deploy
        working-directory: ./packages/website
        env:
          DEPLOY_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_KEY_ID }}
          DEPLOY_ACCESS_SECRET: ${{ secrets.DEPLOY_ACCESS_SECRET }}
        run: |
          wget -q http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
          chmod +x ./ossutil64
          ./ossutil64 config -e oss-accelerate.aliyuncs.com -i $DEPLOY_ACCESS_KEY_ID -k $DEPLOY_ACCESS_SECRET
          ./ossutil64 rm oss://docwiki-next-837556c5/index.html -f
          ./ossutil64 rm oss://docwiki-next-837556c5/favicon.ico -f
          ./ossutil64 cp -r build oss://docwiki-next-837556c5/
